# Generated by Django 6.0.5 on 2026-05-10 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('professor', models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.RESTRICT, to='reviews.professor')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sweetness_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('easiness_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment_text', models.CharField(blank=True, max_length=500, null=True)),
                ('review_date', models.DateField()),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, to='reviews.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, to='reviews.student')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, to='reviews.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, to='reviews.student')),
            ],
            options={
                'db_table': 'Enrollment',
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'semester'), name='enrollment_pk')],
            },
        ),
    ]
