# Generated by Django 6.0.5 on 2026-05-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_easiness_score_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_pk',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
